// Styles
import './assets/css/reset.css';
import './assets/css/layout.css';
import './assets/css/components/header.css';
import './assets/css/components/navbar.css';
import './assets/css/elements/link.css';
import './assets/css/components/footer.css';
// Images
import './assets/images/logo.png';
